# Generated by Django 4.1.4 on 2022-12-16 02:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Applications",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("company", models.CharField(max_length=200)),
                ("role", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Curriculum_vitae",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("location", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Gender",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("F", "Female"),
                            ("M", "Male"),
                            ("NB", "Non-binary"),
                            ("Tr-M", "Transgender Male"),
                            ("Tr-F", "Transgender Female"),
                            ("NA", "Prefer not to say"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("1", "First Class"),
                            ("2", "Second Class Upper"),
                            ("3", "Second Class Lower"),
                            ("4", "Third Class"),
                            ("5", "Passed"),
                            ("6", "Failed"),
                            ("7", "No Grade"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Level_of_edu",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Primary", "Primary School"),
                            ("Secondary", "Secondry School"),
                            ("University", "University"),
                            ("Masters", "Masters"),
                            ("PhD", "PhD"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("profile_image", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField(max_length=2)),
                (
                    "applications",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="interns.applications",
                    ),
                ),
                (
                    "c_v",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="interns.curriculum_vitae",
                    ),
                ),
                (
                    "gender",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="interns.gender"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Referee",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("number", models.BigIntegerField(max_length=11)),
                ("email", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Sector",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Health", "Health"),
                            ("Insurance", "Insurance"),
                            ("Education", "Education"),
                            ("Banking", "Banking"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Work_experience",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("workplace", models.CharField(max_length=200)),
                ("workplace_address", models.TextField()),
                ("job_title", models.CharField(max_length=200)),
                ("job_description", models.TextField()),
                (
                    "referee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="interns.referee",
                    ),
                ),
                (
                    "sector",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="interns.sector"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=40)),
                ("last_name", models.CharField(max_length=40)),
                ("phone", models.BigIntegerField(max_length=11)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="interns.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("school", models.CharField(max_length=200)),
                ("degree", models.CharField(max_length=50)),
                (
                    "Level_of_edu",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="interns.level_of_edu",
                    ),
                ),
                (
                    "grade",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="interns.grade"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="curriculum_vitae",
            name="education",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="interns.education"
            ),
        ),
        migrations.AddField(
            model_name="curriculum_vitae",
            name="work_experience",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="interns.work_experience",
            ),
        ),
    ]
