# Generated by Django 4.1.4 on 2022-12-16 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interns", "0003_alter_applications_id_alter_curriculum_vitae_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="Level_of_edu",
            field=models.CharField(
                choices=[
                    ("Primary", "Primary School"),
                    ("Secondary", "Secondry School"),
                    ("University", "University"),
                    ("Masters", "Masters"),
                    ("PhD", "PhD"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="grade",
            field=models.CharField(
                choices=[
                    ("1", "First Class"),
                    ("2", "Second Class Upper"),
                    ("3", "Second Class Lower"),
                    ("4", "Third Class"),
                    ("5", "Passed"),
                    ("6", "Failed"),
                    ("7", "No Grade"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                choices=[
                    ("F", "Female"),
                    ("M", "Male"),
                    ("NB", "Non-binary"),
                    ("Tr-M", "Transgender Male"),
                    ("Tr-F", "Transgender Female"),
                    ("NA", "Prefer not to say"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="work_experience",
            name="sector",
            field=models.CharField(
                choices=[
                    ("Health", "Health"),
                    ("Insurance", "Insurance"),
                    ("Education", "Education"),
                    ("Banking", "Banking"),
                ],
                max_length=200,
            ),
        ),
        migrations.DeleteModel(name="Gender",),
        migrations.DeleteModel(name="Grade",),
        migrations.DeleteModel(name="Level_of_edu",),
        migrations.DeleteModel(name="Sector",),
    ]
