# Generated by Django 4.1.4 on 2022-12-16 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("interns", "0005_work_experience_owner_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="work_experience",
            name="owner_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="interns.profile",
            ),
        ),
    ]
