# Generated by Django 4.1.4 on 2022-12-17 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("interns", "0006_alter_work_experience_owner_id"),
    ]

    operations = [
        migrations.RemoveField(model_name="curriculum_vitae", name="education",),
        migrations.RemoveField(model_name="curriculum_vitae", name="work_experience",),
        migrations.RemoveField(model_name="profile", name="applications",),
        migrations.RemoveField(model_name="profile", name="c_v",),
        migrations.RemoveField(model_name="work_experience", name="owner_id",),
        migrations.AddField(
            model_name="curriculum_vitae",
            name="owner",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="interns.profile",
            ),
        ),
        migrations.AddField(
            model_name="education",
            name="cv_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="interns.curriculum_vitae",
            ),
        ),
        migrations.AddField(
            model_name="education",
            name="date_ended",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="education",
            name="date_started",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="education",
            name="ongoing",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="work_experience",
            name="cv_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="interns.curriculum_vitae",
            ),
        ),
        migrations.AddField(
            model_name="work_experience",
            name="date_ended",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="work_experience",
            name="date_started",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="work_experience",
            name="ongoing",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="curriculum_vitae",
            name="id",
            field=models.IntegerField(
                editable=False, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="id",
            field=models.IntegerField(
                editable=False, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="work_experience",
            name="id",
            field=models.IntegerField(
                editable=False, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
