# Generated by Django 4.1.4 on 2022-12-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interns", "0007_remove_curriculum_vitae_education_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="grade",
            field=models.CharField(
                choices=[
                    ("First Class", "1"),
                    ("Second Class Upper", "2"),
                    ("Second Class Lower", "3"),
                    ("Third Class", "4"),
                    ("Passed", "5"),
                    ("Failed", "6"),
                    ("No Grade", "7"),
                ],
                max_length=200,
            ),
        ),
    ]
